name: Generate Documentation

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Change to your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r documenation_generation/requirements.txt

    - name: Run documentation script
      run: |
        python documenation_generation/generate_documentation.py

    - name: Commit changes
      run: |
        git config --local user.email "113810873+Interrobang01@users.noreply.github.com"
        git config --local user.name "Interrobang"
        git add README.md
        git commit -m "Update documentation" || echo "No changes to commit"
        git push origin master
